version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: weather-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather-db
    volumes:
      - postgres_data:/var/lib/postgres/data


volumes:
  postgres_data:
    driver: local